Rest client testejä

###
GET http://localhost:10000/Coffee/7504504064263669287

###
GET http://localhost:10000/movies/


###
POST http://localhost:10000/movie/add
Content-Type: application/json

{
  "Name": "randMovie{{$randomInt 0 199}}", 
  "Rating": "{{$randomInt 0 10}}",
  "Desc": "desc",
  "Watch": "{{$localDatetime 'YYYY-MM-DD'}}",
  "Note": "note"
}


###
DELETE ttp://localhost:10000/coffee/delete/4751997750760398000
###
POST http://localhost:10000/Coffee
Content-Type: application/json

{
  "Name": "Hello 1", 
  "Weight": 444, 
  "RoastLevel": 3
}

###

GET https://google.com